import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowRight, Sparkles, Loader2, Image as ImageIcon } from 'lucide-react';
import { Button } from '../components/ui/Button';
import { generationAPI, BASE_URL } from '../services/api';

const Home = () => {
    const [publicGenerations, setPublicGenerations] = useState<any[]>([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const loadGenerations = async () => {
            try {
                const data = await generationAPI.getPublicGenerations(8);
                setPublicGenerations(data.generations);
            } catch (error) {
                console.error('Failed to load public generations:', error);
            } finally {
                setLoading(false);
            }
        };

        loadGenerations();
    }, []);

    return (
        <div className="min-h-screen bg-white">
            {/* Hero Section */}
            <section className="pt-32 pb-20 px-6 max-w-7xl mx-auto">
                {/* Changed to always be 2 columns to keep logo on right for mobile */}
                <div className="grid grid-cols-2 gap-6 md:gap-12 items-center">
                    <motion.div
                        initial={{ opacity: 0, x: -20 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ duration: 0.8 }}
                    >
                        <h1 className="text-4xl sm:text-5xl md:text-8xl font-bold mb-4 md:mb-8 font-display text-primary-900 leading-tight">
                            Imagine<br />
                            <span className="text-primary-600">Create</span><br />
                            <span className="text-primary-500">Inspire</span>
                        </h1>

                        <p className="text-sm sm:text-lg md:text-2xl text-primary-700 mb-6 md:mb-10 max-w-lg leading-relaxed">
                            Transform your words into breathtaking visuals with Vision's transformer-based diffusion model.
                        </p>

                        <div className="flex flex-col sm:flex-row gap-3 md:gap-4">
                            <Link to="/sign-in">
                                <Button size="lg" variant="primary" className="w-full sm:w-auto text-sm md:text-base bg-primary-600 hover:bg-primary-700 text-white border-none py-2 md:py-3">
                                    <Sparkles size={18} className="mr-2" />
                                    Start Creating
                                </Button>
                            </Link>
                            <Link to="/docs">
                                <Button size="lg" variant="outline" className="w-full sm:w-auto text-sm md:text-base border-primary-200 text-primary-700 hover:bg-primary-50 py-2 md:py-3 hidden sm:flex">
                                    Docs
                                </Button>
                            </Link>
                        </div>
                    </motion.div>

                    <motion.div
                        initial={{ opacity: 0, x: 20 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ duration: 0.8, delay: 0.2 }}
                        className="flex justify-end"
                    >
                        <img
                            src="/Ininsicologo.png"
                            alt="Vision AI Logo"
                            className="w-full max-w-md object-contain drop-shadow-2xl"
                        />
                    </motion.div>
                </div>
            </section>

            {/* Community Showcase Section */}
            <section className="py-12 md:py-20 px-6 bg-white">
                <div className="max-w-7xl mx-auto">
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                        transition={{ duration: 0.6 }}
                        className="text-center mb-10 md:mb-16"
                    >
                        <h2 className="text-3xl md:text-6xl font-bold text-primary-900 mb-4 font-display">
                            Community Creations
                        </h2>
                        <p className="text-base md:text-xl text-primary-600 max-w-2xl mx-auto">
                            Explore stunning images generated by our AI model
                        </p>
                    </motion.div>

                    {/* Image Grid */}
                    <div className="relative overflow-hidden min-h-[300px] md:min-h-[400px]">
                        {loading ? (
                            <div className="flex flex-col items-center justify-center py-20">
                                <Loader2 className="w-12 h-12 text-primary-500 animate-spin mb-4" />
                                <p className="text-primary-600">Loading masterpieces...</p>
                            </div>
                        ) : publicGenerations && publicGenerations.length > 0 ? (
                            <motion.div
                                initial={{ opacity: 0 }}
                                whileInView={{ opacity: 1 }}
                                viewport={{ once: true }}
                                className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3 md:gap-6"
                            >
                                {publicGenerations.map((gen, index) => (
                                    <motion.div
                                        key={gen._id}
                                        initial={{ opacity: 0, y: 20 }}
                                        whileInView={{ opacity: 1, y: 0 }}
                                        viewport={{ once: true }}
                                        transition={{ delay: index * 0.1 }}
                                        className="group relative aspect-square rounded-xl md:rounded-2xl overflow-hidden cursor-pointer shadow-lg hover:shadow-2xl transition-all duration-300 bg-primary-50"
                                    >
                                        <img
                                            src={gen.imageUrl.startsWith('data:') || gen.imageUrl.startsWith('http') ? gen.imageUrl : `${BASE_URL}${gen.imageUrl}`}
                                            alt={gen.prompt}
                                            className="absolute inset-0 w-full h-full object-cover transition-transform duration-500 group-hover:scale-110"
                                            loading="lazy"
                                            onError={(e) => {
                                                (e.target as HTMLImageElement).src = 'https://placehold.co/400x400/png?text=Generation+Error';
                                            }}
                                        />
                                        <div className="absolute inset-0 bg-gradient-to-t from-primary-900/90 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                                            <div className="absolute bottom-0 left-0 right-0 p-4 transform translate-y-4 group-hover:translate-y-0 transition-transform duration-300">
                                                <p className="text-white text-xs md:text-sm font-medium line-clamp-2">{gen.prompt}</p>
                                                <div className="flex items-center mt-2 text-white/80 text-xs text-[10px] md:text-xs">
                                                    <Sparkles size={12} className="mr-1" />
                                                    <span>AI Generated</span>
                                                </div>
                                            </div>
                                        </div>
                                    </motion.div>
                                ))}
                            </motion.div>
                        ) : (
                            <div className="text-center py-20 bg-primary-50 rounded-3xl border-2 border-dashed border-primary-200">
                                <ImageIcon className="w-16 h-16 text-primary-300 mx-auto mb-4" />
                                <p className="text-xl text-primary-600 font-medium">No public generations yet.</p>
                                <p className="text-primary-500 mt-2">Be the first to create one!</p>
                            </div>
                        )}
                    </div>

                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                        className="text-center mt-10 md:mt-16"
                    >
                        <Link to="/sign-in">
                            <Button size="lg" variant="primary" className="bg-primary-600 hover:bg-primary-700 text-white shadow-xl hover:shadow-2xl btn-hover-lift w-full sm:w-auto">
                                <Sparkles size={20} className="mr-2" />
                                Create Your Own
                                <ArrowRight size={20} className="ml-2" />
                            </Button>
                        </Link>
                    </motion.div>
                </div>
            </section>

            {/* Meet the Team Section */}
            <section className="py-12 md:py-20 px-6 bg-white border-t border-primary-50">
                <div className="max-w-7xl mx-auto">
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                        transition={{ duration: 0.6 }}
                        className="text-center mb-10 md:mb-16"
                    >
                        <h2 className="text-3xl md:text-6xl font-bold text-primary-900 mb-4 font-display">
                            Meet the Team
                        </h2>
                        <p className="text-base md:text-xl text-primary-600 max-w-2xl mx-auto">
                            The minds behind Vision AI
                        </p>
                    </motion.div>

                    {/* Changed to responsive layout: single column on mobile, two columns on desktop */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8 md:gap-12 max-w-4xl mx-auto mb-16 md:mb-20">
                        {/* Huzaifa */}
                        <motion.div
                            initial={{ opacity: 0, y: 20 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            viewport={{ once: true }}
                            transition={{ duration: 0.6 }}
                            className="bg-white rounded-2xl p-6 md:p-8 shadow-xl border border-primary-100 hover:shadow-2xl transition-all hover:-translate-y-1"
                        >
                            <div className="flex flex-col items-center text-center">
                                <div className="w-32 h-32 md:w-40 md:h-40 rounded-full overflow-hidden mb-6 border-4 border-primary-50 shadow-md">
                                    <img
                                        src="/Huzaifa.jpeg"
                                        alt="Huzaifa"
                                        className="w-full h-full object-cover"
                                    />
                                </div>
                                <h3 className="text-xl md:text-2xl font-bold text-primary-900 mb-2 font-display">
                                    Huzaifa
                                </h3>
                                <p className="text-primary-600 font-semibold mb-4 text-xs md:text-sm uppercase tracking-wider">Full Stack & DevOps Lead</p>
                                <p className="text-primary-700 text-sm md:text-base leading-relaxed">
                                    Architected the complete frontend and backend infrastructure, implementing robust CI/CD pipelines to ensure seamless deployment and scalability.
                                </p>
                            </div>
                        </motion.div>

                        {/* Arslan */}
                        <motion.div
                            initial={{ opacity: 0, y: 20 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            viewport={{ once: true }}
                            transition={{ duration: 0.6, delay: 0.2 }}
                            className="bg-white rounded-2xl p-6 md:p-8 shadow-xl border border-primary-100 hover:shadow-2xl transition-all hover:-translate-y-1"
                        >
                            <div className="flex flex-col items-center text-center">
                                <div className="w-32 h-32 md:w-40 md:h-40 rounded-full overflow-hidden mb-6 border-4 border-primary-50 shadow-md">
                                    <img
                                        src="/Arslan.png"
                                        alt="Arslan"
                                        className="w-full h-full object-cover"
                                    />
                                </div>
                                <h3 className="text-xl md:text-2xl font-bold text-primary-900 mb-2 font-display">
                                    Arslan
                                </h3>
                                <p className="text-primary-600 font-semibold mb-4 text-xs md:text-sm uppercase tracking-wider">AI Engineer & Integration Specialist</p>
                                <p className="text-primary-700 text-sm md:text-base leading-relaxed">
                                    Developed and trained the core AI model, optimizing performance and integrating the machine learning pipeline directly with the web application.
                                </p>
                            </div>
                        </motion.div>
                    </div>

                    {/* Collaboration Note */}
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                        transition={{ delay: 0.4 }}
                        className="text-center border-t border-primary-50 pt-10 md:pt-12"
                    >
                        <p className="text-base md:text-lg text-primary-800 font-medium mb-4">
                            Made at COMSATS Islamabad Abbottabad Campus
                        </p>
                        <div className="flex justify-center items-center gap-4">
                            <img
                                src="/Comsats.png"
                                alt="COMSATS University"
                                className="h-12 md:h-16 object-contain opacity-90 hover:opacity-100 transition-opacity"
                            />
                            <span className="text-xl md:text-2xl font-bold text-primary-900 font-display hidden sm:inline">
                                COMSATS
                            </span>
                        </div>
                    </motion.div>
                </div>
            </section>
        </div>
    );
};

export default Home;
